<?php

$produtos = array(
   0 => array('nome' => 'motorista', 'preco' => '5.000', 'descricao' => 'macaquinho com chapéu preto', 'imagem' => 'nft0.jpg'),
   1 => array('nome' => 'rei', 'preco' => '3.000', 'descricao' => 'macaquinho rei colorido', 'imagem' => 'nft1.jpg'),
   2 => array('nome' => 'jorge curioso', 'preco' => '4.500', 'descricao' => 'macaquinho pescador', 'imagem' => 'nft2.jpg'),
   3 => array('nome' => 'azuleto', 'preco' => '1.500', 'descricao' => 'macaquinho chato azul', 'imagem' => 'nft3.jpg'),
   4 => array('nome' => 'capitão', 'preco' => '12.000', 'descricao' => 'macaquinho capitão lazer nos olhos', 'imagem' => 'nft4.jpg'),
   5 => array('nome' => 'americano', 'preco' => '3.000', 'descricao' => 'macaquinho radical motoqueiro', 'imagem' => 'nft5.jpg'),
   6 => array('nome' => 'robô', 'preco' => '5.500', 'descricao' => 'macaquinho sem olho robótico', 'imagem' => 'nft6.jpg'),
   7 => array('nome' => 'pink', 'preco' => '11.000', 'descricao' => 'macaquinho rosa de chapéu', 'imagem' => 'nft7.jpg'),
   8 => array('nome' => 'cowboy', 'preco' => '40.000', 'descricao' => 'macaquinho de rodeio', 'imagem' => 'nft8.jpg'),
   9 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft9.jpg'),
   10 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft10.jpg'),
   11 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft11.jpg'),
   12 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft12.jpg'),
   13 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft13.jpg'),
   14 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft14.jpg'),
   15 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft15.jpg'),
   16 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft16.jpg'),
   17 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft17.jpg'),
   18 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft18.jpg'),
   19 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft19.jpg'),
   20 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft20.jpg'),
   21 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft21.jpg'),
   22 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft22.jpg'),
   23 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft23.jpg'),
   24 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft24.jpg'),
   25 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft25.jpg'),
   26 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft26.jpg'),
   27 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft27.jpg'),
   28 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft28.jpg'),
   29 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft29.jpg'),
   30 => array('nome' => 'punk', 'preco' => '3.000', 'descricao' => 'macaquinho encrenqueiro', 'imagem' => 'nft30.jpg'),
);

?>